
import type { Skill } from './types';

// This data is now used as a template for new users,
// but completion status is managed in Firestore per user.
export const initialSkills: Omit<Skill, 'completed'>[] = [
    {
      id: 1,
      title: 'Pre-Drive Vehicle Check',
      teachingPoints: [
        'Walk around the car to check for leaks, flat tires, and obstructions.',
        'Inspect tire tread and inflation level.',
        'Check for working headlights, turn signals, brake lights, and reverse lights.',
        'Make sure windows and mirrors are clean and unobstructed.',
        'Ensure windshield wiper blades are functional and fluid levels are adequate.',
      ],
    },
    {
      id: 2,
      title: 'Proper Seating & Mirror Adjustment',
      teachingPoints: [
        'Sit upright with back firmly against the seat and hands at 9 and 3 o\'clock.',
        'Adjust seat so knees are slightly bent and heel can pivot between pedals.',
        'Adjust head restraint to the middle of the head for safety.',
        'Position the steering wheel 10–12 inches from chest and below shoulder height.',
        'Adjust mirrors using the blind-zone reduction method for full coverage.',
      ],
    },
    {
      id: 3,
      title: 'Starting & Stopping the Engine',
      teachingPoints: [
        'Ensure the car is in Park (or Neutral for manual transmissions) before starting.',
        'Start the engine smoothly and check for warning lights.',
        'Practice shifting into drive, reverse, and park correctly.',
        'Turn off the engine properly and engage the parking brake.',
        'Understand the function of dashboard indicators and gauges.',
      ],
    },
    {
      id: 4,
      title: 'Checking Blind Spots',
      teachingPoints: [
        'Turn your head briefly over your shoulder before changing lanes.',
        'Identify areas not visible in mirrors and where vehicles can hide.',
        'Combine mirror checks with shoulder checks every time.',
        'Practice identifying blind spots while stationary and in motion.',
        'Be especially alert for pedestrians, cyclists, and motorcycles.',
      ],
    },
    {
      id: 5,
      title: 'Hand-to-Hand Steering',
      teachingPoints: [
        'Keep hands at 9 and 3 o\'clock for better control and airbag safety.',
        'Use hand-to-hand technique without crossing arms for all turns.',
        'Practice gentle corrections to avoid oversteering.',
        'Return the wheel smoothly to center after a turn.',
        'Use consistent grip pressure to maintain control on curves.',
      ],
    },
    {
      id: 6,
      title: 'Smooth Braking & Acceleration',
      teachingPoints: [
        'Use the ball of your foot on pedals, not the toes or heel.',
        'Avoid slamming the brakes—apply steady, even pressure.',
        'Ease off the gas to slow before braking.',
        'Accelerate gradually to avoid wheel spin or jerky starts.',
        'Practice stopping at a consistent distance before stop lines.',
      ],
    },
    {
      id: 7,
      title: 'Backing Up',
      teachingPoints: [
        'Look over your shoulder out the rear window while reversing.',
        'Use mirrors and backup camera as additional aids—not replacements.',
        'Back up slowly and be prepared to brake.',
        'Turn the wheel in the direction you want the rear to go.',
        'Practice backing in a straight line and around corners.',
      ],
    },
    {
      id: 8,
      title: 'Reference Points & Vehicle Positioning',
      teachingPoints: [
        'Learn visual markers for front, sides, and rear bumper locations.',
        'Practice pulling within 6–12 inches of curbs on both sides.',
        'Use parking lines and cones to judge distances.',
        'Understand how vehicle height and seating position affect reference points.',
        'Use landmarks like side mirrors or hood center for consistency.',
      ],
    },
    {
      id: 9,
      title: 'Right and Left Turns',
      teachingPoints: [
        'Signal at least 100 feet before the turn.',
        'Slow before the turn, then accelerate gently out.',
        'Turn into the correct lane based on markings and traffic.',
        'Check for pedestrians, bikes, and oncoming traffic.',
        'Look through the turn and steer smoothly.',
      ],
    },
    {
      id: 10,
      title: 'Lane Positioning',
      teachingPoints: [
        'Center position: most common and safest.',
        'Left position: used to avoid hazards on the right.',
        'Right position: used when turning or avoiding oncoming traffic.',
        'Stay centered in the lane unless conditions require repositioning.',
        'Avoid drifting due to distraction or poor steering habits.',
      ],
    },
    {
      id: 11,
      title: 'Intersections & Right-of-Way',
      teachingPoints: [
        'Identify who has the right of way before proceeding.',
        'Stop fully at stop signs and behind crosswalks or lines.',
        'Scan in all directions before entering.',
        'Yield to pedestrians and cross traffic when required.',
        'Do not enter an intersection unless you can clear it completely.',
      ],
    },
    {
      id: 12,
      title: 'Commentary Driving',
      teachingPoints: [
        'Say out loud what you see, what you’re doing, and what you plan to do.',
        'Call out signs, hazards, signals, and other vehicles.',
        'Helps improve awareness and decision-making.',
        'Reinforces good scanning habits and risk assessment.',
        'Builds confidence in complex driving environments.',
      ],
    },
    {
      id: 13,
      title: 'IPDE System',
      teachingPoints: [
        'Identify potential hazards early (cars, bikes, people, signals).',
        'Predict possible outcomes (e.g., merging, crossing).',
        'Decide on your safest option quickly.',
        'Execute the decision confidently and smoothly.',
        'Use during all driving to stay proactive, not reactive.',
      ],
    },
    {
      id: 14,
      title: 'Following Distance (4-Second Rule)',
      teachingPoints: [
        'Count “one-thousand-one” to “one-thousand-four” behind a marker.',
        'Increase time in bad weather or behind large vehicles.',
        'Add time for higher speeds or heavier vehicles.',
        'Never tailgate—even in slow traffic.',
        'More space gives more reaction time and visibility.',
      ],
    },
    {
      id: 15,
      title: 'Safe Lane Changes',
      teachingPoints: [
        'Check mirrors and blind spot before moving over.',
        'Signal in advance to communicate intent.',
        'Maintain or slightly increase speed during the change.',
        'Move smoothly into the new lane—no sharp swerves.',
        'Cancel signal and adjust following distance.',
      ],
    },
    {
      id: 16,
      title: 'Passing Other Vehicles',
      teachingPoints: [
        'Only pass in legal passing zones with clear visibility.',
        'Signal, check blind spots, and accelerate to pass safely.',
        'Return to your lane when you see the entire vehicle in your mirror.',
        'Do not exceed the speed limit while passing.',
        'Never pass on hills, curves, or in intersections.',
      ],
    },
    {
      id: 17,
      title: 'Parallel Parking',
      teachingPoints: [
        'Line up with car ahead, 2–3 feet away.',
        'Reverse and turn sharply to enter the space.',
        'Straighten wheels and center the car.',
        'Stay within 6–12 inches of the curb.',
        'Use the Dutch Reach to check for cyclists before opening doors.',
      ],
    },
    {
      id: 18,
      title: 'Angle & Perpendicular Parking',
      teachingPoints: [
        'Signal before turning into a parking spot.',
        'Align side mirror or wheel with the parking line before turning.',
        'Turn slowly and center the vehicle.',
        'Stop before hitting any curb or car ahead.',
        'Always check surroundings before backing out.',
      ],
    },
    {
      id: 19,
      title: 'Three-Point & Two-Point Turns',
      teachingPoints: [
        'Use only when there are no safe driveways or roundabouts.',
        'Check traffic in all directions before beginning.',
        'Signal clearly and move slowly through each part of the turn.',
        'Use a driveway or wide shoulder if available for a two-point turn.',
        'Practice in low-traffic areas first.',
      ],
    },
    {
      id: 20,
      title: 'Roundabout Navigation',
      teachingPoints: [
        'Yield to all traffic in the roundabout before entering.',
        'Stay in your lane and do not stop while inside.',
        'Signal when preparing to exit.',
        'Use the correct entry lane based on your direction.',
        'Do not change lanes or pass inside the roundabout.',
      ],
    },
    {
      id: 21,
      title: 'Freeway Merging',
      teachingPoints: [
        'Use entrance ramp to reach traffic speed.',
        'Signal and look for a safe gap in traffic.',
        'Merge smoothly—do not stop on the ramp.',
        'Yield to freeway traffic; they have the right-of-way.',
        'Keep checking mirrors and blind spots.',
      ],
    },
    {
      id: 22,
      title: 'Freeway Lane Changes & Exits',
      teachingPoints: [
        'Plan exits early and move into the correct lane in advance.',
        'Signal at least 4 seconds before changing lanes.',
        'Use mirrors and blind spot checks frequently.',
        'Do not slow down on the freeway when exiting.',
        'Follow posted exit ramp speed limits.',
      ],
    },
    {
      id: 23,
      title: 'Driving on Rural Roads',
      teachingPoints: [
        'Reduce speed on gravel and narrow lanes.',
        'Watch for wildlife, farm equipment, and hidden driveways.',
        'Increase following distance due to reduced traction.',
        'Be alert at uncontrolled intersections and railroad crossings.',
        'Avoid overcorrecting if you go off the road.',
      ],
    },
    {
      id: 24,
      title: 'Driving in the City',
      teachingPoints: [
        'Use center lane to avoid parked cars and buses.',
        'Cover the brake in high-risk areas.',
        'Scan ahead constantly for hazards and distractions.',
        'Avoid passing on busy, congested streets.',
        'Expect sudden stops and unpredictable behavior.',
      ],
    },
    {
      id: 25,
      title: 'Driving at Night',
      teachingPoints: [
        'Use low beams when other cars are present.',
        'Turn on headlights 30 minutes before sunset.',
        'Watch for glare and use night setting on mirrors.',
        'Increase following distance and reduce speed.',
        'Scan for animals and pedestrians.',
      ],
    },
    {
      id: 26,
      title: 'Driving in Rain or Snow',
      teachingPoints: [
        'Use low beams and windshield wipers.',
        'Slow down and leave extra space.',
        'Avoid hard braking or sudden moves.',
        'Turn on defroster if windows fog up.',
        'Be aware of black ice, especially on bridges.',
      ],
    },
    {
      id: 27,
      title: 'Emergency Vehicle Protocol',
      teachingPoints: [
        'Pull over to the nearest curb when lights and sirens are approaching.',
        'Stop completely and wait until the emergency vehicle has passed.',
        'Never block intersections or driveways.',
        'If in a roundabout, exit before stopping.',
        'Signal and check surroundings before rejoining traffic.',
      ],
    },
    {
      id: 28,
      title: 'Understanding Vehicle Technology',
      teachingPoints: [
        'Learn how features like ABS, lane assist, and cruise control work.',
        'Know limitations—driver assistance is not autopilot.',
        'Read the owner’s manual or ask your dealership for a demo.',
        'Practice with safety tech in calm environments first.',
        'Don’t rely solely on sensors or cameras.',
      ],
    },
    {
      id: 29,
      title: 'Avoiding Distractions',
      teachingPoints: [
        'Silence or store phones while driving.',
        'Set music, climate, and navigation before driving.',
        'Avoid eating, grooming, or reaching for objects.',
        'Stay focused in conversations—pull over if needed.',
        'Know that multitasking increases crash risk.',
      ],
    },
    {
      id: 30,
      title: 'Managing Peer Pressure & Emotions',
      teachingPoints: [
        'Only allow passengers you feel comfortable with.',
        'Set boundaries for music volume, talking, and distractions.',
        'Never drive angry, upset, or emotionally impaired.',
        'Know how to say “no” to risky suggestions.',
        'Recognize when to pause or cancel a drive for safety.',
      ],
    },
  ];
